"""empty message

Revision ID: 0562c95a6447
Revises: 5ef21779a1c8
Create Date: 2023-04-26 17:06:58.594566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0562c95a6447'
down_revision = '5ef21779a1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parecord', schema=None) as batch_op:
        batch_op.alter_column('person_type',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=False)
        batch_op.alter_column('le_type',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parecord', schema=None) as batch_op:
        batch_op.alter_column('le_type',
               existing_type=sa.String(length=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('person_type',
               existing_type=sa.String(length=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
