"""empty message

Revision ID: 065c144be0fe
Revises: 15aa8b450877
Create Date: 2023-04-23 23:23:11.529635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065c144be0fe'
down_revision = '15aa8b450877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=100), nullable=False))

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
