"""empty message

Revision ID: 0dd0d9c634ca
Revises: ad2d0b6b844a
Create Date: 2023-02-20 17:34:54.631136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd0d9c634ca'
down_revision = 'ad2d0b6b844a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_constraint('email_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.create_foreign_key('email_ibfk_1', 'admin', ['receiver_id'], ['id'])

    # ### end Alembic commands ###
