"""empty message

Revision ID: 2ca432908caf
Revises: 2422464f303a
Create Date: 2023-02-17 00:59:02.868219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ca432908caf'
down_revision = '2422464f303a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_num', sa.String(length=100), nullable=False))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('phone_num')

    # ### end Alembic commands ###
