"""empty message

Revision ID: 516a22bae21d
Revises: 1518b0a530f3
Create Date: 2023-02-20 19:58:24.249572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516a22bae21d'
down_revision = '1518b0a530f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'admin', ['sender'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sender')

    # ### end Alembic commands ###
