"""empty message

Revision ID: 5f5f467666ca
Revises: d8cf8e71e36a
Create Date: 2023-04-06 20:29:26.403409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f5f467666ca'
down_revision = 'd8cf8e71e36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_vehicle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vp', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['visitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_internal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.drop_table('temp_vehicle')
    # ### end Alembic commands ###
