"""empty message

Revision ID: 7734b23a5ecd
Revises: 065c144be0fe
Create Date: 2023-04-26 00:01:07.519863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7734b23a5ecd'
down_revision = '065c144be0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PARecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('person_type', sa.Integer(), nullable=False),
    sa.Column('le_type', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PARecord')
    # ### end Alembic commands ###
