"""empty message

Revision ID: 8d09d6515bd8
Revises: 4fb0d6325190
Create Date: 2023-05-20 14:16:16.459408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d09d6515bd8'
down_revision = '4fb0d6325190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('varecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vp', sa.String(length=12), nullable=False),
    sa.Column('vehicle_type', sa.String(length=2), nullable=False),
    sa.Column('le_type', sa.String(length=2), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=12),
               existing_nullable=False)

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('vp',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=12),
               existing_nullable=False)

    with op.batch_alter_table('parecord', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=12),
               existing_nullable=False)

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=12),
               existing_nullable=False)

    with op.batch_alter_table('temp_vehicle', schema=None) as batch_op:
        batch_op.alter_column('vp',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=12),
               existing_nullable=False)

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('temp_vehicle', schema=None) as batch_op:
        batch_op.alter_column('vp',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('parecord', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('vp',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('varecord')
    # ### end Alembic commands ###
