"""empty message

Revision ID: 956310dcda23
Revises: 8d09d6515bd8
Create Date: 2023-05-25 17:06:19.289648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956310dcda23'
down_revision = '8d09d6515bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('le_type', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('le_type')

    # ### end Alembic commands ###
