"""empty message

Revision ID: a10e28cda61f
Revises: ddf96f6cda5c
Create Date: 2023-04-12 16:19:37.315454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a10e28cda61f'
down_revision = 'ddf96f6cda5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('room', sa.Integer(), nullable=False))
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('room')
        batch_op.drop_column('building')

    # ### end Alembic commands ###
