"""empty message

Revision ID: bf1db6637f46
Revises: 11ba81da1caf
Create Date: 2023-02-16 13:25:00.775739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1db6637f46'
down_revision = '11ba81da1caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('phone_num', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal', sa.Boolean(), nullable=False))

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_index('phone_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.create_index('phone_num', ['phone_num'], unique=False)

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('is_internal')

    op.drop_table('visitor')
    # ### end Alembic commands ###
