"""empty message

Revision ID: c0ac92f5bada
Revises: 7734b23a5ecd
Create Date: 2023-04-26 00:15:40.142265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0ac92f5bada'
down_revision = '7734b23a5ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PARecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('person_type', sa.Integer(), nullable=False),
    sa.Column('le_type', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('parecord')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parecord',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('person_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('le_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('PARecord')
    # ### end Alembic commands ###
