"""empty message

Revision ID: f4f3d7a617fe
Revises: d5438da9e76f
Create Date: 2023-05-19 02:31:44.868139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f3d7a617fe'
down_revision = 'd5438da9e76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapmark',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapmark')
    # ### end Alembic commands ###
